services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install huggingface_hub[hf_xet]  # Fix Xet storage warning
    startCommand: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PORT
        value: 10000